### PR TITLE
Finalizing work done till now

### PR DESCRIPTION
**Pull request by aditya-verma**

### CODE REVIEW

**Review by AmriteshR — APPROVED** [review]
Final Update Information Page requires some work and CV page for admin left.

**Comment by Ashutosh-khetan** [comment]
Done reviewing

**Review by Ashutosh-khetan — DISMISSED** [review]
Done reviewing.

**Review by T3rex — COMMENTED** [review]
.

**Review by T3rex — APPROVED** [review]
kuch bhi

**Comment by aditya-verma** [comment]
Merging was blocked due to unsigned approve.

**Pull request merged**
